cache filters to dev redis

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -50,3 +50,31 @@ jobs:
             git commit -m "updated by GitHub Actions workflow"
             git push origin develop
           fi
+
+  cache-codelist-rules:
+    needs: build
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'push' }} # only push to the redis cache on PUSH
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          # Number of commits to fetch. 0 indicates all history for all branches and tags.
+          fetch-depth: 0
+
+      - name: POST filters.json to func-iati-redis-cacher-dev
+        run: | 
+          FILE_COMMIT_SHA=$(git log -1 --format='%H' -- './filters.json')
+          echo $FILE_COMMIT_SHA
+          HTTP_CODE=$(curl --write-out "%{http_code}\n" \
+          --location --request POST 'https://func-iati-redis-cacher-dev.azurewebsites.net/api/pvt/cache?key=dssFilters&commitsha='$FILE_COMMIT_SHA \
+          --header 'x-functions-key: '$DEFAULT_KEY \
+          --header 'Content-Type: application/json' \
+          --data-binary '@./filters.json' \
+          --output curl_out.txt \
+          --silent )
+          echo $HTTP_CODE
+          if [[ $HTTP_CODE != '200' ]] ; then
+            echo "Reponse is not 200 from func-iati-redis-cacher-dev, check error logs"
+            cat curl_out.txt
+            exit 1
+          fi
